import type { Metadata } from 'next'
import React from 'react'
import {GoogleTagManager, GoogleAnalytics} from '@next/third-parties/google'
import { Noto_Sans } from 'next/font/google'
import '../styles/globals.css'
import QueryProvider from '../providers/query'
import StoreProvider from '../providers/store'
import IdleTimerWrapper from '../providers/idleTimerWrapper'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import EventListener from '../providers/EventListener'
import { GA_ID, GTM_ID } from '../utils/config'

const notosans = Noto_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Radpretation',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notosans.className}>
      <GoogleTagManager gtmId={GTM_ID}/>
      <GoogleAnalytics gaId={GA_ID} />
        <StoreProvider>
          <EventListener>
            <QueryProvider>
              <IdleTimerWrapper>
                <AppRouterCacheProvider>
                 
                  {children}
                  
                  </AppRouterCacheProvider>
              </IdleTimerWrapper>
            </QueryProvider>
          </EventListener>
        </StoreProvider>
      </body>
    </html>
  )
}
