# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment

on:
  push:
    branches: [ "main" ]
  

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: "build image" 
      run: docker build -t "mehtanitin/project" .
    - name: "login to docker-hub" 
      run: echo "${{secrets.DOCKER_HUD_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUD_USERNAME}} --password-stdin
      #// run: docker login -u mehtanitin 
      #// run:  echo "dckr_pat_d-ogxze-Eb1bvU75ogmiBY4DN"  
    - name: "push image on docker hub "
      run: docker push mehtanitin/project:latest
